-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "quiet",
		},
	},
}